debug: true
host_address: :3000
metrics_address: :9000
sentry_dsn: https://c0374926d8324d0bbf72279e921f3935@sentry.k8s.golang-mts-teta.ru/32
jaeger_collector: http://jaeger-instance-collector.observability:14268/api/traces
db:
  host: localhost
  port: 5432
  name: tasks
  ssl: disable