debug: true
host_address: :3000
auth_address: auth:4000
analytics_address: analytics:4000
sentry_dsn: https://c0374926d8324d0bbf72279e921f3935@sentry.k8s.golang-mts-teta.ru/32
jaeger_collector: http://jaeger-instance-collector.observability:14268/api/traces
db:
  user: team41
  password: mNgdxQTbhVGd
  host: 91.185.93.23
  port: 5432
  name: team41
  ssl: disable
kafka:
  brokers:
    - 91.185.95.87:9094
  topic_analytics: team41-tasks
  topic_mailsender: team41-emails
